name: CI

on:
  push:
    branches: [main, bisect-node-16-breakage]
  pull_request:
    branches: [main, bisect-node-16-breakage]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: [8]
        node: [16]
        npm: [8.5.5, 8.6, 8.7, 8.8, 8.9, 8.10.0, 8.11.0, 8.12.0, 8.12.1, 8.12.2, 8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install npm ${{ matrix.npm }}
      run: npm install -g npm@${{ matrix.npm }}
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Install ESLint@${{  matrix.eslint  }}
      run: npm install eslint@${{  matrix.eslint  }}
    - name: Test
      run: npm run test-cov
